analyzer:
  strong-mode: true

  errors:
    strong_mode_not_instantiated_bound: ignore

linter:
  rules:
    # Errors
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - comment_references
    - empty_statements
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    # Style
    - always_declare_return_types
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
#    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - prefer_is_not_empty
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interp
    # Pub Rules
    - package_names