name: farmers_markets
description: A simple farmer's market web app to demo Angular2Dart
version: 0.0.1
author: Sam Baron <sam.baron@sent.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  dart_sass_transformer: ^0.5.0
  intl: ^0.15.0
  ng_bootstrap: any

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

analyzer:
  strong-mode: true

transformers:
- dart_sass_transformer:
    executable: sassc
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter